"""Review report (milestone M7): what is documented, what Paul still has to review.

`pci review` writes docs/review.md from the committed data only, so it is reproducible and
a test can check it is current. Paul reviews by editing the YAML files
(`review_status: reviewed`, `lang_review: reviewed`) and running `pci review` again.
"""

import json
from collections import Counter
from pathlib import Path

from pci import ROOT
from pci.build import load_curated
from pci.index import INDEX_PATH
from pci.mediation import MEDIATION_DIR, load_sheets
from pci.places import IMAGES_PATH, PLACES_PATH, load_yaml
from pci.summaries import SUMMARIES_PATH

REVIEW_PATH = ROOT / "docs" / "review.md"
SITE = "https://paulbenard01.github.io/Mapatrimoine/"
THEME_NAMES = {
    "social-festive": "Pratiques sociales et festives",
    "rituals": "Rituels",
    "performing-arts": "Arts du spectacle",
    "oral": "Traditions et expressions orales",
    "physical": "Pratiques physiques",
    "games": "Jeux",
    "know-how": "Savoirs et savoir-faire",
}
CONFIDENCE_ORDER = {"low": 0, "medium": 1, "high": 2, None: 3}


def _mark(done: bool) -> str:
    return "✓" if done else "·"


def _cell(text: str) -> str:
    return text.replace("|", "\\|")


def collect(mediation_dir: Path = MEDIATION_DIR) -> dict:
    index = json.loads(INDEX_PATH.read_text(encoding="utf-8"))["elements"]
    published = [e for e in index if not e["unpublished"]]
    curated = {c["id"]: c for c in load_curated()}
    sheets = {s["id"]: s for s in load_sheets(mediation_dir)}
    places, images = load_yaml(PLACES_PATH), load_yaml(IMAGES_PATH)
    return {
        "published": published,
        "curated": curated,
        "sheets": sheets,
        "places": places,
        "images": images,
        "summaries": load_yaml(SUMMARIES_PATH),
    }


def coverage(data: dict) -> list[tuple[str, int]]:
    curated, sheets, short = data["curated"], data["sheets"], data["summaries"]
    total = len(data["published"])
    places_from = Counter("PCI Lab" if p.get("pcilab") else "web" for p in data["places"].values())
    pictures = Counter(i["source"] for i in data["images"].values())
    return [
        ("Published elements", total),
        ("On the map", len(curated) + len(data["places"])),
        ("  places from curated files", len(curated)),
        ("  places from PCI Lab", places_from["PCI Lab"]),
        ("  places from the fiche or other web pages", places_from["web"]),
        ("With a picture", len(data["images"])),
        ("  Wikimedia Commons", pictures["commons"]),
        ("  fiche image via PCI Lab", pictures["pcilab"]),
        ("  photo from the fiche", pictures["fiche"]),
        ("Documented (summary, timing)", len(curated)),
        ("  timing reviewed", sum(c["review_status"] == "reviewed" for c in curated.values())),
        (
            "  EN summary reviewed",
            sum(c["summary"]["lang_review"] == "reviewed" for c in curated.values()),
        ),
        ("With a mediation sheet", len(sheets)),
        ("  sheet reviewed", sum(s["review_status"] == "reviewed" for s in sheets.values())),
        ("Short summary only (no timing yet)", len(short)),
        ("  events", sum(e["kind"] == "event" for e in short.values())),
        ("  practices", sum(e["kind"] == "practice" for e in short.values())),
        ("  summary reviewed", sum(e["review_status"] == "reviewed" for e in short.values())),
        ("No summary yet", total - len(curated) - len(short)),
    ]


def render(data: dict) -> str:
    published = {e["id"]: e for e in data["published"]}
    curated, sheets = data["curated"], data["sheets"]
    lines = [
        "# Review status",
        "",
        "Generated by `pci review` from the committed data; do not edit by hand. "
        "A test fails when it is out of date.",
        "",
        "How to review an element: open its page on the site, check the summary, places and timing "
        "against the official fiche and the web sources, fix the YAML if needed, then set "
        "`review_status: reviewed` (facts and timing) and "
        "`summary.lang_review: reviewed` (English) "
        "in `data/curated/<id>.yaml`, and `review_status` / `lang_review` in "
        "`data/mediation/<id>.yaml` for the sheet. Run `pci build && pci review`.",
        "",
        "## Coverage",
        "",
        "| | Elements |",
        "|---|---:|",
    ]
    lines += [f"| {label.replace('  ', '— ')} | {n} |" for label, n in coverage(data)]
    lines += ["", "## Documented elements", ""]
    lines += [
        "Lowest timing confidence first. Columns: timing reviewed, English summary reviewed, "
        "mediation sheet written, sheet reviewed.",
        "",
        "| Element | Kind | Confidence | Timing | EN | Sheet | Sheet reviewed |",
        "|---|---|---|:-:|:-:|:-:|:-:|",
    ]

    def order(c: dict) -> tuple:
        confidence = (c.get("timing") or {}).get("confidence")
        return (c["review_status"] == "reviewed", CONFIDENCE_ORDER[confidence], c["id"])

    for c in sorted(curated.values(), key=order):
        title = c.get("title_fr") or published.get(c["id"], {}).get("title", c["id"])
        sheet = sheets.get(c["id"])
        confidence = (c.get("timing") or {}).get("confidence") or "–"
        link = f"[{_cell(title)}]({SITE}?id={c['id']})"
        sheet_cell = f"[✓]({SITE}?id={c['id']}&sheet=1)" if sheet else "·"
        lines.append(
            f"| {link} | {c['kind']} | {confidence} | {_mark(c['review_status'] == 'reviewed')} "
            f"| {_mark(c['summary']['lang_review'] == 'reviewed')} | {sheet_cell} "
            f"| {_mark(bool(sheet) and sheet['review_status'] == 'reviewed')} |"
        )
    short = data["summaries"]
    lines += [
        "",
        "## Short summaries",
        "",
        "Elements not curated yet carry a short summary in `data/summaries.yaml` "
        "(no timing). Columns: facts reviewed, English reviewed.",
        "",
        "| Element | Kind | Facts | EN |",
        "|---|---|:-:|:-:|",
    ]
    for ident, entry in short.items():
        title = published.get(ident, {}).get("title", ident)
        lines.append(
            f"| [{_cell(title)}]({SITE}?id={ident}) | {entry['kind']} "
            f"| {_mark(entry['review_status'] == 'reviewed')} "
            f"| {_mark(entry['summary']['lang_review'] == 'reviewed')} |"
        )
    lines += ["", "## Not curated yet, by theme", ""]
    lines += ["| Theme | Short summary | No summary |", "|---|---:|---:|"]
    themes = Counter(e["theme"] for i, e in published.items() if i not in curated)
    with_short = Counter(e["theme"] for i, e in published.items() if i in short)
    for theme, n in sorted(themes.items(), key=lambda t: (-t[1], t[0])):
        lines.append(
            f"| {THEME_NAMES.get(theme, theme)} | {with_short[theme]} | {n - with_short[theme]} |"
        )
    return "\n".join(lines) + "\n"


def write_review(path: Path = REVIEW_PATH) -> str:
    text = render(collect())
    path.write_text(text, encoding="utf-8")
    return text
